/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empresa;


import DAO.ComissionadoJpaController;
import DAO.EmpregadoJpaController;
import DAO.HoristaJpaController;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import model.Comissionado;
import model.Empregado;
import model.Horista;

/**
 *
 * 
 */

public class FrameEmpresa extends javax.swing.JFrame {

    
    public static final EntityManagerFactory emf = Persistence.createEntityManagerFactory("EmpresaPU");
    public static final ComissionadoJpaController CJPA = new ComissionadoJpaController(emf);
    public static final HoristaJpaController HJPA = new HoristaJpaController(emf);

    public FrameEmpresa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        tb_EmpComTx = new javax.swing.JTextField();
        btnCad_Com = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        tb_EmpComTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tb_IDCOM = new javax.swing.JTextField();
        btn_CarregaCom = new javax.swing.JButton();
        lbl_comNome = new javax.swing.JLabel();
        lbl_ComSobNome = new javax.swing.JLabel();
        lbl_ComCpf = new javax.swing.JLabel();
        lbl_ComTx = new javax.swing.JLabel();
        lbl_ComTotalVen = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lbl_ComVen = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tb_SobNomeCom = new javax.swing.JTextField();
        tb_CpfCom = new javax.swing.JTextField();
        tb_NomeCom = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnCad_Hor = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        tb_IDHOR = new javax.swing.JTextField();
        btn_CarregaHor = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tb_SobNomeHor = new javax.swing.JTextField();
        tb_CpfHor = new javax.swing.JTextField();
        tb_NomeHor = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        tb_EmpHorPreço = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tb_EmpHorHT = new javax.swing.JTextField();
        lbl_hornome = new javax.swing.JLabel();
        lbl_horsobnome = new javax.swing.JLabel();
        lbl_horcpf = new javax.swing.JLabel();
        lbl_horprhora = new javax.swing.JLabel();
        lbl_hortotal = new javax.swing.JLabel();
        lbl_horVenc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel14.setText("Taxa de Comissão:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 160, 110, 14);

        tb_EmpComTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_EmpComTxActionPerformed(evt);
            }
        });
        jPanel1.add(tb_EmpComTx);
        tb_EmpComTx.setBounds(10, 180, 100, 20);

        btnCad_Com.setText("Cadastrar Comissionado");
        btnCad_Com.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCad_ComActionPerformed(evt);
            }
        });
        jPanel1.add(btnCad_Com);
        btnCad_Com.setBounds(10, 210, 250, 23);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(190, 40, 0, 70);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(170, 50, 0, 110);

        jLabel5.setText("Total de vendas:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 160, 110, 14);
        jPanel1.add(tb_EmpComTotal);
        tb_EmpComTotal.setBounds(130, 180, 100, 20);

        jLabel6.setText("ID Comissionado:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(280, 50, 110, 14);
        jPanel1.add(tb_IDCOM);
        tb_IDCOM.setBounds(280, 70, 90, 20);

        btn_CarregaCom.setText("Buscar");
        btn_CarregaCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CarregaComActionPerformed(evt);
            }
        });
        jPanel1.add(btn_CarregaCom);
        btn_CarregaCom.setBounds(380, 70, 90, 23);

        lbl_comNome.setText("Nome:");
        jPanel1.add(lbl_comNome);
        lbl_comNome.setBounds(280, 120, 310, 14);

        lbl_ComSobNome.setText("Sobrenome:");
        jPanel1.add(lbl_ComSobNome);
        lbl_ComSobNome.setBounds(280, 140, 310, 14);

        lbl_ComCpf.setText("CPF:");
        jPanel1.add(lbl_ComCpf);
        lbl_ComCpf.setBounds(280, 160, 310, 14);

        lbl_ComTx.setText("Taxa de Comissão:");
        jPanel1.add(lbl_ComTx);
        lbl_ComTx.setBounds(280, 180, 310, 14);

        lbl_ComTotalVen.setText("Total de vendas: ");
        jPanel1.add(lbl_ComTotalVen);
        lbl_ComTotalVen.setBounds(280, 200, 310, 14);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(270, 10, 10, 230);

        lbl_ComVen.setText("Vencimento:");
        jPanel1.add(lbl_ComVen);
        lbl_ComVen.setBounds(280, 220, 310, 14);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Cadastrar Comissionado:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(10, 20, 310, 15);

        jLabel7.setText("Nome:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 50, 110, 14);

        jLabel12.setText("Sobrenome:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 80, 140, 14);

        jLabel16.setText("CPF:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 110, 110, 14);

        tb_SobNomeCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_SobNomeComActionPerformed(evt);
            }
        });
        jPanel1.add(tb_SobNomeCom);
        tb_SobNomeCom.setBounds(80, 80, 170, 20);
        jPanel1.add(tb_CpfCom);
        tb_CpfCom.setBounds(80, 110, 90, 20);
        jPanel1.add(tb_NomeCom);
        tb_NomeCom.setBounds(80, 50, 170, 20);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Informações do empregado comissionado:");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(280, 100, 310, 15);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("Buscar empregado comissionado:");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(280, 20, 310, 15);

        jTabbedPane1.addTab("Comissionado", jPanel1);

        jPanel4.setLayout(null);

        btnCad_Hor.setText("Cadastrar Horista");
        btnCad_Hor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCad_HorActionPerformed(evt);
            }
        });
        jPanel4.add(btnCad_Hor);
        btnCad_Hor.setBounds(10, 210, 250, 23);
        jPanel4.add(jSeparator3);
        jSeparator3.setBounds(190, 40, 0, 70);
        jPanel4.add(jSeparator5);
        jSeparator5.setBounds(170, 50, 0, 110);

        jLabel9.setText("ID Horista:");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(280, 50, 110, 14);
        jPanel4.add(tb_IDHOR);
        tb_IDHOR.setBounds(280, 70, 90, 20);

        btn_CarregaHor.setText("Buscar");
        btn_CarregaHor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CarregaHorActionPerformed(evt);
            }
        });
        jPanel4.add(btn_CarregaHor);
        btn_CarregaHor.setBounds(380, 70, 90, 23);

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator8);
        jSeparator8.setBounds(270, 10, 10, 230);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText("Cadastrar Horista:");
        jPanel4.add(jLabel29);
        jLabel29.setBounds(10, 20, 310, 15);

        jLabel10.setText("Nome:");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(10, 50, 70, 14);

        jLabel18.setText("Sobrenome:");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(10, 80, 100, 14);

        jLabel19.setText("CPF:");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(10, 110, 60, 14);

        tb_SobNomeHor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_SobNomeHorActionPerformed(evt);
            }
        });
        jPanel4.add(tb_SobNomeHor);
        tb_SobNomeHor.setBounds(80, 80, 170, 20);
        jPanel4.add(tb_CpfHor);
        tb_CpfHor.setBounds(80, 110, 90, 20);
        jPanel4.add(tb_NomeHor);
        tb_NomeHor.setBounds(80, 50, 170, 20);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("Informações do empregado Horista:");
        jPanel4.add(jLabel30);
        jLabel30.setBounds(280, 100, 310, 15);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setText("Buscar empregado horista:");
        jPanel4.add(jLabel31);
        jLabel31.setBounds(280, 20, 310, 15);
        jPanel4.add(tb_EmpHorPreço);
        tb_EmpHorPreço.setBounds(10, 180, 100, 20);

        jLabel4.setText("Preço/Hora:");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(10, 160, 120, 14);

        jLabel11.setText("Horas Trabalhadas:");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(130, 160, 120, 10);
        jPanel4.add(tb_EmpHorHT);
        tb_EmpHorHT.setBounds(130, 180, 100, 20);

        lbl_hornome.setText("Nome:");
        jPanel4.add(lbl_hornome);
        lbl_hornome.setBounds(280, 120, 310, 14);

        lbl_horsobnome.setText("Sobrenome:");
        jPanel4.add(lbl_horsobnome);
        lbl_horsobnome.setBounds(280, 140, 310, 14);

        lbl_horcpf.setText("CPF:");
        jPanel4.add(lbl_horcpf);
        lbl_horcpf.setBounds(280, 160, 310, 14);

        lbl_horprhora.setText("Preço/Hora:");
        jPanel4.add(lbl_horprhora);
        lbl_horprhora.setBounds(280, 180, 310, 14);

        lbl_hortotal.setText("Horas Trabalhadas:");
        jPanel4.add(lbl_hortotal);
        lbl_hortotal.setBounds(280, 200, 310, 14);

        lbl_horVenc.setText("Vencimento:");
        jPanel4.add(lbl_horVenc);
        lbl_horVenc.setBounds(280, 220, 310, 14);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Horista", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_SobNomeHorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_SobNomeHorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_SobNomeHorActionPerformed

    private void btnCad_HorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCad_HorActionPerformed
        
        Horista hor = new Horista(Double.parseDouble(tb_EmpHorPreço.getText()), 
                Double.parseDouble(tb_EmpHorHT.getText()), 
                tb_NomeHor.getText(), tb_SobNomeHor.getText(), tb_CpfHor.getText());
        
        HJPA.create(hor);
        
        tb_EmpHorPreço.setText(null);
        tb_EmpHorHT.setText(null);
        tb_NomeHor.setText(null);
        tb_SobNomeHor.setText(null);
        tb_CpfHor.setText(null);
        
        JOptionPane.showMessageDialog(null,"Horista Id:"
                +hor.getId().toString()+" Cadastrado!"); 
    }//GEN-LAST:event_btnCad_HorActionPerformed

    private void tb_SobNomeComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_SobNomeComActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_SobNomeComActionPerformed

    private void btnCad_ComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCad_ComActionPerformed
        
        Comissionado com = new Comissionado(Double.parseDouble(tb_EmpComTx.getText()), 
                Double.parseDouble(tb_EmpComTotal.getText()), 
                tb_NomeCom.getText(), tb_SobNomeCom.getText(), tb_CpfCom.getText());
        
        CJPA.create(com);
        
        tb_EmpComTx.setText(null);
        tb_EmpComTotal.setText(null);
        tb_NomeCom.setText(null);
        tb_SobNomeCom.setText(null);
        tb_CpfCom.setText(null);
        
        JOptionPane.showMessageDialog(null,"Comissionado Id:"
                +com.getId().toString()+" Cadastrado!");
        
    }//GEN-LAST:event_btnCad_ComActionPerformed

    private void tb_EmpComTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_EmpComTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_EmpComTxActionPerformed

    private void btn_CarregaComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CarregaComActionPerformed
      Comissionado com = CJPA.findComissionado(Long.parseLong(tb_IDCOM.getText()));
      Double venc = com.Calcvenc(com.getTxComissao(), com.getTotalVenda());
      
      
      lbl_comNome.setText("Nome: " + com.getNome());
      lbl_ComSobNome.setText("Sobrenome: " + com.getSobrenome());
      lbl_ComCpf.setText("CPF: " + com.getCpf());
      lbl_ComTx.setText("Taxa de comissão: " + com.getTxComissao()+"%");
      lbl_ComTotalVen.setText("Total de vendas: R$" + com.getTotalVenda());
      lbl_ComVen.setText("Vencimento: R$" + venc);
      
    }//GEN-LAST:event_btn_CarregaComActionPerformed

    private void btn_CarregaHorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CarregaHorActionPerformed
      Horista hor = HJPA.findHorista(Long.parseLong(tb_IDHOR.getText()));
      Double venc = hor.CalcVenc(hor.getPrecoHora(), hor.getHrTrab());
      
      
      lbl_hornome.setText("Nome: " + hor.getNome());
      lbl_horsobnome.setText("Sobrenome: " + hor.getSobrenome());
      lbl_horcpf.setText("CPF: " + hor.getCpf());
      lbl_horprhora.setText("Preço por hora: " + hor.getPrecoHora()+"R$");
      lbl_hortotal.setText("Horas trabalhadas: " + hor.getHrTrab());
      lbl_horVenc.setText("Vencimento: " + venc +"R$");
    }//GEN-LAST:event_btn_CarregaHorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCad_Com;
    private javax.swing.JButton btnCad_Hor;
    private javax.swing.JButton btn_CarregaCom;
    private javax.swing.JButton btn_CarregaHor;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_ComCpf;
    private javax.swing.JLabel lbl_ComSobNome;
    private javax.swing.JLabel lbl_ComTotalVen;
    private javax.swing.JLabel lbl_ComTx;
    private javax.swing.JLabel lbl_ComVen;
    private javax.swing.JLabel lbl_comNome;
    private javax.swing.JLabel lbl_horVenc;
    private javax.swing.JLabel lbl_horcpf;
    private javax.swing.JLabel lbl_hornome;
    private javax.swing.JLabel lbl_horprhora;
    private javax.swing.JLabel lbl_horsobnome;
    private javax.swing.JLabel lbl_hortotal;
    private javax.swing.JTextField tb_CpfCom;
    private javax.swing.JTextField tb_CpfHor;
    private javax.swing.JTextField tb_EmpComTotal;
    private javax.swing.JTextField tb_EmpComTx;
    private javax.swing.JTextField tb_EmpHorHT;
    private javax.swing.JTextField tb_EmpHorPreço;
    private javax.swing.JTextField tb_IDCOM;
    private javax.swing.JTextField tb_IDHOR;
    private javax.swing.JTextField tb_NomeCom;
    private javax.swing.JTextField tb_NomeHor;
    private javax.swing.JTextField tb_SobNomeCom;
    private javax.swing.JTextField tb_SobNomeHor;
    // End of variables declaration//GEN-END:variables
}
